# Generated by Django 4.0.2 on 2022-03-01 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_text',
            new_name='post_text',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_text',
            new_name='choice_text',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='meet_date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
