# Generated by Django 4.0.4 on 2022-05-03 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isToggled', models.BooleanField(default=True)),
                ('enrolled_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.profile')),
            ],
        ),
    ]
