# Generated by Django 4.0.2 on 2022-04-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_courses',
            field=models.ManyToManyField(to='studyapp.Course'),
        ),
    ]
