# Generated by Django 4.0.2 on 2022-04-17 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='studyapp.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='meetings',
            field=models.ManyToManyField(to='studyapp.Meeting'),
        ),
    ]
