# Generated by Django 4.0.2 on 2022-04-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_meeting_course_profile_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='buddies',
            field=models.ManyToManyField(to='studyapp.Profile'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(default=None, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(default=None, verbose_name='Start time'),
        ),
    ]
