# Generated by Django 4.0.2 on 2022-04-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_course_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='course_fullform',
        ),
    ]
