# Generated by Django 4.0.2 on 2022-04-27 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_remove_profile_friends_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_request',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='studyapp.profile'),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='studyapp.profile'),
        ),
    ]
