# Generated by Django 4.0.2 on 2022-03-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='DEP', max_length=200),
        ),
    ]
