# Generated by Django 4.0.2 on 2022-04-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_meeting_buddies_meeting_end_time_meeting_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='post_date',
            field=models.DateTimeField(default=None, verbose_name='date posted'),
        ),
    ]
