# Generated by Django 4.0.2 on 2022-04-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0004_rename_course_title_course_course_fullform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_fullform',
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(default='DEP', max_length=10),
        ),
    ]
