# Generated by Django 4.0.2 on 2022-04-28 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0004_alter_friend_request_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='studyapp.Profile'),
        ),
    ]
