# Generated by Django 4.0.2 on 2022-04-18 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0005_alter_meeting_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted'),
        ),
    ]
